### ISSUE TITLE
Use IOBinding to avoid unnecessary data copy and unnecessary CPU<->GPU transfers.

### ISSUE THREAD

**Issue by DavidLangworthy** [triton-inference-server/onnxruntime_backend#19]

**Comment by RORO-ML** [comment]
Hello, thank you for the great repo. How are the plans for `onnxruntime.capi.onnxruntime_inference_collection.IOBinding` objects and the infer with `session.run_with_iobinding(io_binding) `. I/O binding leads to a significant speed up to a lot of models and the model that I would like to serve :)

**Comment by DavidLangworthy** [comment]
Thanks.  It's on the list.  Do you have any perf numbers you could share?

**Comment by RORO-ML** [comment]
I'm still not on my main machine, atm I only have these stats:

-> GPT2-small, batch_size=1, sequence_length=1, past_sequence_length=256
`torch_latency=14.53, onnxruntime_latency=21.72, onnxruntime_io_binding_latency=3.00`

For transformer-based models, IO binding strongly affects the inference speed, especially for larger sequence lengths.

**Comment by denti** [comment]
Hi, @DavidLangworthy from my side. I do inference of huge transformer models in ensemble mode.
And for now, all parts of the huge model are concatenated through CPU memory. This gives me a bottleneck.
Some numbers:
1. I use DGX. When I test 2xpatrts of the model concatenated in ensemble (2x onnx files 8GB each) on 2x GPUs, I get about 2.4 infer when I use ORT backend.
2. When I run 4 x same ensemble pipelines on 8 GPUs. I expect that throughput should increase 4x. But due to CPU throughput bottleneck I get only 6 infer/sec.

Concurrency: 2, throughput: 2.4 infer/sec, latency 854605 usec
Concurrency: 3, throughput: 3 infer/sec, latency 986427 usec
Concurrency: 4, throughput: 4 infer/sec, latency 1022323 usec
Concurrency: 5, throughput: 4.4 infer/sec, latency 1039965 usec
Concurrency: 6, throughput: 5.4 infer/sec, latency 1106724 usec
Concurrency: 7, throughput: 5.8 infer/sec, latency 1166150 usec
Concurrency: 8, throughput: 5.8 infer/sec, latency 1311293 usec
Concurrency: 9, throughput: 5.8 infer/sec, latency 1453779 usec
Concurrency: 10, throughput: 5.8 infer/sec, latency 1602709 usec
Concurrency: 11, throughput: 5.8 infer/sec, latency 1753706 usec
Concurrency: 12, throughput: 5.8 infer/sec, latency 1879825 usec
Concurrency: 13, throughput: 5.2 infer/sec, latency 2199301 usec
Concurrency: 14, throughput: 5.2 infer/sec, latency 2312499 usec
Concurrency: 15, throughput: 5.2 infer/sec, latency 2430365 usec
Concurrency: 16, throughput: 4.8 infer/sec, latency 2895568 usec
Concurrency: 17, throughput: 5.2 infer/sec, latency 2644198 usec
Concurrency: 18, throughput: 4.6 infer/sec, latency 3067973 usec
Concurrency: 19, throughput: 4.8 infer/sec, latency 3057375 usec
Concurrency: 20, throughput: 4.8 infer/sec, latency 3364095 usec

**Comment by askhade** [comment]
enable io binding -> https://github.com/triton-inference-server/onnxruntime_backend/pull/42
