### ISSUE TITLE
Build without docker

### ISSUE THREAD

**Issue by vignesh34v** [triton-inference-server/onnxruntime_backend#40]
How to build onnxruntime_backend without using docker container? 

I have built onnxruntime from the source.

**Comment by CoderHam** [comment]
You will need to use the TRITON_ONNXRUNTIME_INCLUDE_PATHS and TRITON_ONNXRUNTIME_LIB_PATHS cmake arguments instead of TRITON_BUILD_CONTAINER_VERSION. 

Keep in mind you will need to unpack your built onnxruntime similarly to as it is done in [CMakeLists.txt].(https://github.com/triton-inference-server/onnxruntime_backend/blob/main/CMakeLists.txt#L378-L411)

@GuanLuo do we want to document this in the ReadMe?

**Comment by askhade** [comment]
@CoderHam : Yes we should. There is one more issue logged for the same. Can you pick this up?

**Comment by CoderHam** [comment]
@askhade I think my answer above clarified the same. I can provide the user more assistance if they require but this issue can be closed for now.
