### ISSUE TITLE
ORT backend always returns tensor on CPU

### ISSUE THREAD

**Issue by aklife97** [triton-inference-server/onnxruntime_backend#73]
**Description**
The ORT backend always returns output tensors on CPU even when the instance is on GPU - when run using BLS through the python backend.

**Expected behavior**
The output tensor should be on the GPU when the instance kind is GPU for the ONNX model.

**Comment by CoderHam** [comment]
@Tabrizian can you look into the same

**Comment by askhade** [comment]
This issue explains the current limitation and why output is always on CPU : https://github.com/triton-inference-server/server/issues/3364

**Comment by askhade** [comment]
Once triton-inference-server/server#3364 is merged we will enable output binding to gpus in ort backend.

**Comment by Slyne** [comment]
Any update ?

**Comment by askhade** [comment]
@Slyne This will be available in triton 22.02 release.

**Comment by Slyne** [comment]
@askhade  Thank you for informing!

**Comment by vu0607** [comment]
@askhade I serving encoder-decoder model (TrOCR) on Triton onnx backend. I meet a problem:
- First, I call and get output from encoder model in server. Afterthat, because output on GPU, I need to transfer to CPU for converting to numpy before call output from decoder model on server. It make botteneck. Hope you can help me with issue. Thanks a lot.
